// <auto-generated />
using System;
using HienTangToc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HienTangToc.Migrations
{
    [DbContext(typeof(HientocDbcontext))]
    [Migration("20240908122834_Hientangtoc")]
    partial class Hientangtoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HienTangToc.Models.HSalonModel", b =>
                {
                    b.Property<int>("HSalonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HSalonId"));

                    b.Property<int>("Idnh")
                        .HasColumnType("int");

                    b.Property<int>("Idsl")
                        .HasColumnType("int");

                    b.HasKey("HSalonId");

                    b.HasIndex("Idnh");

                    b.HasIndex("Idsl");

                    b.ToTable("HSalonModels");
                });

            modelBuilder.Entity("HienTangToc.Models.MSalonModel", b =>
                {
                    b.Property<int>("MSalonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MSalonId"));

                    b.Property<int>("Idnm")
                        .HasColumnType("int");

                    b.Property<int>("Idsl")
                        .HasColumnType("int");

                    b.HasKey("MSalonId");

                    b.HasIndex("Idnm");

                    b.HasIndex("Idsl");

                    b.ToTable("MSalonModels");
                });

            modelBuilder.Entity("HienTangToc.Models.NguoihienModel", b =>
                {
                    b.Property<int>("Idnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idnh"));

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gioitinh")
                        .HasColumnType("int");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngayhien")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idnh");

                    b.ToTable("NguoihienModels");
                });

            modelBuilder.Entity("HienTangToc.Models.NguoimuonModel", b =>
                {
                    b.Property<int>("Idnm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idnm"));

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gioitinh")
                        .HasColumnType("int");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaydangky")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguyennhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idnm");

                    b.ToTable("NguoimuonModels");
                });

            modelBuilder.Entity("HienTangToc.Models.SalonModel", b =>
                {
                    b.Property<int>("Idsl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idsl"));

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thoigianhd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uudai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idsl");

                    b.ToTable("SalonModels");
                });

            modelBuilder.Entity("HienTangToc.Models.TocModel", b =>
                {
                    b.Property<int>("Idtoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idtoc"));

                    b.Property<string>("Dodaitoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loaitoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("Idtoc");

                    b.ToTable("TocModels");
                });

            modelBuilder.Entity("HienTangToc.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HienTangToc.Models.HSalonModel", b =>
                {
                    b.HasOne("HienTangToc.Models.NguoihienModel", "NguoihienModel")
                        .WithMany("HSalonModels")
                        .HasForeignKey("Idnh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HienTangToc.Models.SalonModel", "SalonModel")
                        .WithMany("HSalonModels")
                        .HasForeignKey("Idsl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoihienModel");

                    b.Navigation("SalonModel");
                });

            modelBuilder.Entity("HienTangToc.Models.MSalonModel", b =>
                {
                    b.HasOne("HienTangToc.Models.NguoimuonModel", "NguoimuonModel")
                        .WithMany("MSalonModels")
                        .HasForeignKey("Idnm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HienTangToc.Models.SalonModel", "SalonModel")
                        .WithMany("MSalonModels")
                        .HasForeignKey("Idsl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoimuonModel");

                    b.Navigation("SalonModel");
                });

            modelBuilder.Entity("HienTangToc.Models.NguoihienModel", b =>
                {
                    b.Navigation("HSalonModels");
                });

            modelBuilder.Entity("HienTangToc.Models.NguoimuonModel", b =>
                {
                    b.Navigation("MSalonModels");
                });

            modelBuilder.Entity("HienTangToc.Models.SalonModel", b =>
                {
                    b.Navigation("HSalonModels");

                    b.Navigation("MSalonModels");
                });
#pragma warning restore 612, 618
        }
    }
}
